[tool.poetry]
name = "devenv"
version = "0"
description = ""
authors = ["Domen Ko≈æar <domen@dev.si>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pillow = "^9.5.0"
cairosvg = "^2.7.0"
mkdocs-markdownextradata-plugin = "^0.2.5"
mkdocs-material = "^9.1.6"
mkdocs-rss-plugin = {git = "https://github.com/cachix/mkdocs-rss-plugin", rev = "no-git"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
