[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
clap_complete = "4.5.7"
clap_mangen = "0.2.22"
devenv = { path = "../devenv" }
miette.workspace = true
