name: "PR Test"

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"
      - "requirements.in"
      - "requirements.txt"

  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (tag or branch) to test'
        required: true
        default: 'main'
        type: string

concurrency:
  group: "${{ github.workflow }}-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.ref }}"
  cancel-in-progress: true

jobs:
  pipeline:
    name: pipeline (${{ matrix.system }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - system: aarch64-linux
            runs-on: '["self-hosted", "linux", "ARM64"]'
          - system: x86_64-linux
            runs-on: '["self-hosted", "linux", "X64"]'
          - system: aarch64-darwin
            runs-on: '["self-hosted", "macOS", "ARM64"]'
          - system: x86_64-darwin
            runs-on: '["macos-15-intel"]'

    uses: ./.github/workflows/per-system-pipeline.yml
    secrets: inherit
    with:
      system: ${{ matrix.system }}
      runs-on: ${{ matrix.runs-on }}
      ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || '' }}
