name: "Test"

on:
  workflow_call:
    inputs:
      ref:
        description: "Git ref to checkout"
        required: false
        type: string
      system:
        description: "System to test on"
        required: true
        type: string
      runs-on:
        description: "Runner to use"
        required: true
        type: string
      nixpkgs-input:
        description: "An optional nixpkgs input to test against"
        required: false
        type: string

jobs:
  tests:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Configure Cachix
        uses: cachix/cachix-action@v16
        with:
          name: devenv
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build devenv
        run: |
          path=$(nix build -L --print-out-paths)
          echo "$path/bin" >> $GITHUB_PATH
      - name: Test tasks outside shell
        run: devenv tasks run devenv:enterShell
      - name: Run devenv-test-cli
        run: |
          devenv \
            ${{ inputs.nixpkgs-input && format('--override-input nixpkgs {0}', inputs.nixpkgs-input) || '' }} \
            shell devenv-test-cli
      - name: Run tests
        run: |
          devenv-run-tests \
            ${{ inputs.nixpkgs-input && format('--override-input nixpkgs {0}', inputs.nixpkgs-input) || '' }} \
            run tests


  direnv:
    name: direnv (${{ inputs.system }})
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Configure Cachix
        uses: cachix/cachix-action@v16
        with:
          name: devenv
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build devenv
        run: |
          path=$(nix build -L --print-out-paths)
          echo "$path/bin" >> $GITHUB_PATH
      - run: |
          mkdir -p ~/.config/direnv/
          cat > ~/.config/direnv/direnv.toml << 'EOF'
          [global]
          strict_env = true
          EOF

          devenv_dir=$PWD
          tmp="$(mktemp -d)"
          pushd "$tmp"
            nix shell nixpkgs#direnv -c devenv \
              ${{ inputs.nixpkgs-input && format('--override-input nixpkgs {0}', inputs.nixpkgs-input) || '' }} \
              --override-input devenv path:$devenv_dir?dir=src/modules \
              init
          popd

  fish-zsh:
    name: zsh/fish (${{ inputs.system }})
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Configure Cachix
        uses: cachix/cachix-action@v16
        with:
          name: devenv
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build devenv
        run: |
          path=$(nix build -L --print-out-paths)
          echo "$path/bin" >> $GITHUB_PATH
      - name: Test devenv in fish and zsh
        run: |
          nix shell nixpkgs#zsh -c zsh -c "devenv version"
          nix shell nixpkgs#fish -c fish -c "devenv version"
